{
  "openapi": "3.0.1",
  "info": {
    "title": "Ace",
    "description": "This service provides functionality for Real-Time ABS Compliant Email.This API supports operations to register product based on incoming abs and campaign request.",
        "x-metadata":{
           "capability": "EXPERIENCE API",
           "tags":["active", "experience"]
  },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    },
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://ace-v1-app-p.aws-k8s.abbvienet.com",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/api/v1/ace/convention": {
      "post": {
        "tags": [
          "Real-Time ABS Compliant Email"
        ],
        "summary": "Real-Time ABS Compliant Email",
        "description": "Registers product and validate the abs request.",
        "operationId": "absValidation",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AbsValidationRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "401": {
            "description": "Unauthorized - Authentication failed or user does not have permissions for the requested operation.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponseDto"
                },
                "example": {
                  "status": "ERROR",
                  "errors": [
                    {
                      "errorCode": "UNAUTHORIZED",
                      "code": "10001",
                      "message": "unauthorized error"
                    }
                  ]
                }
              }
            }
          },
          "200": {
            "description": "Success - Product saved successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CampaignResponse"
                },
                "example": {
                  "status": "SUCCESS",
                  "guid": "b6c1f2b8-5666-4aa0-ba53-920f61033080",
                  "result": "8ef1#191997f2614",
                  "requestId": "8ef1#191997f2614"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error - Unexcepted error occurred on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponseDto"
                },
                "example": {
                  "status": "ERROR",
                  "errors": [
                    {
                      "errorCode": "SERVER ERROR",
                      "code": "10001",
                      "message": "server error"
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request - Validation error or invalid input provided.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponseDto"
                },
                "example": {
                  "status": "ERROR",
                  "errors": [
                    {
                      "errorCode": "BAD_REQUEST",
                      "code": "10000",
                      "message": "exposureId must not be empty"
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found - The requested resource could not be found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponseDto"
                },
                "example": {
                  "timestamp": "2024-08-28T15:00:30.115+0000",
                  "status": 404,
                  "error": "Not Found",
                  "message": "No message available",
                  "path": "/api/v1/ace/convention"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/ace/campaign": {
      "post": {
        "tags": [
          "Real-Time ABS Compliant Email"
        ],
        "summary": "Real-Time ABS Compliant Email",
        "description": "Registers product and validate the campaign request.",
        "operationId": "campaign",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CampaignRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "404": {
            "description": "Not Found - The requested resource could not be found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponseDto"
                },
                "example": {
                  "timestamp": "2024-08-28T15:00:30.115+0000",
                  "status": 404,
                  "error": "Not Found",
                  "message": "No message available",
                  "path": "/api/v1/ace/campaign"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Authentication failed or user does not have permissions for the requested operation.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponseDto"
                },
                "example": {
                  "status": "ERROR",
                  "errors": [
                    {
                      "errorCode": "UNAUTHORIZED",
                      "code": "10001",
                      "message": "unauthorized error"
                    }
                  ]
                }
              }
            }
          },
          "200": {
            "description": "Success - Product saved successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CampaignResponse"
                },
                "example": {
                  "status": "SUCCESS",
                  "guid": "b6c1f2b8-5666-4aa0-ba53-920f61033080",
                  "result": "8ef1#191997f2614",
                  "requestId": "8ef1#191997f2614"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error - Unexcepted error occurred on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponseDto"
                },
                "example": {
                  "status": "ERROR",
                  "errors": [
                    {
                      "errorCode": "SERVER ERROR",
                      "code": "10001",
                      "message": "server error"
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request - Validation error or invalid input provided.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponseDto"
                },
                "example": {
                  "status": "ERROR",
                  "errors": [
                    {
                      "errorCode": "BAD_REQUEST",
                      "code": "10000",
                      "message": "exposureId must not be empty"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "AbsValidationRequest": {
        "required": [
          "scanGroupCode"
        ],
        "type": "object",
        "properties": {
          "npi": {
            "type": "string",
            "description": "HCP Npi",
            "example": "1902185168"
          },
          "acid": {
            "type": "string",
            "description": "HCP Acid",
            "example": "5304576"
          },
          "firstName": {
            "type": "string",
            "description": "HCP First Name",
            "example": "Lindsey"
          },
          "lastName": {
            "type": "string",
            "description": "HCP Last Name",
            "example": "Stenshoel"
          },
          "address1": {
            "type": "string",
            "description": "HCP Address1",
            "example": "1276 W River St Ste 100"
          },
          "zip": {
            "type": "string",
            "description": "HCP Zip",
            "example": "83702"
          },
          "email": {
            "type": "string",
            "description": "HCP Email",
            "example": "lstenshoel@accessbhs.com"
          },
          "scanGroupCode": {
            "type": "string",
            "description": "HCP Scan Group Code",
            "example": "EXP-00098"
          }
        },
        "description": "The 'AbsValidationRequest' object captures essential details of an API request and response for real time abs compliant email."
      },
      "ErrorDto": {
        "type": "object",
        "properties": {
          "errorCode": {
            "type": "string",
            "enum": [
              "BAD_REQUEST",
              "INVALID_SCANNED_GROUP_CODE",
              "CLIENT_ERROR",
              "SERVER_ERROR",
              "NO_RECORD_FOUND",
              "HCP_IS_NOT_IN_APPROVED_PRODUCT"
            ]
          },
          "code": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "ErrorResponseDto": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "enum": [
              "SUCCESS",
              "ERROR"
            ]
          },
          "errors": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ErrorDto"
            }
          }
        }
      },
      "CampaignResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "The textual status of the operation.",
            "example": "BAD_REQUEST",
            "enum": [
              "SUCCESS",
              "ERROR"
            ]
          },
          "guid": {
            "type": "string",
            "description": "HCP guid",
            "example": "b6c1f2b8-5666-4aa0-ba53-920f61033080"
          },
          "result": {
            "type": "string",
            "description": "HCP result",
            "example": "b222#191987c40ee"
          },
          "requestId": {
            "type": "string",
            "description": "HCP requestId",
            "example": "b222#191987c40ee"
          }
        },
        "description": "The 'CampaignResponse' object provides detailed information about the outcome of a real time abs compliant email."
      },
      "CampaignRequest": {
        "required": [
          "acid",
          "exposureId"
        ],
        "type": "object",
        "properties": {
          "acid": {
            "type": "string",
            "description": "HCP Acid",
            "example": "5304576"
          },
          "triggerEmail": {
            "type": "string",
            "description": "HCP Trigger Email",
            "example": "lstenshoel@accessbhs.com"
          },
          "franchiseBrandIndication": {
            "type": "string",
            "description": "HCP Franchise Brand Indication",
            "example": "Humira"
          },
          "exposureId": {
            "type": "string",
            "description": "HCP Exposure Id",
            "example": "123"
          },
          "primaryValue": {
            "type": "string",
            "description": "HCP Primary Value",
            "example": "001"
          },
          "dynamicValue": {
            "type": "string",
            "description": "HCP Dynamic Value",
            "example": "001"
          }
        },
        "description": "The 'CampaignRequest' object captures essential details of an API request and response for real time abs compliant email."
      }
    }
  }
}